### ISSUE TITLE
syzzzf.box.json中的icons

### ISSUE THREAD

**Issue by ghost** [songyangzz/QuantumultX#7]
icons中的两条链接都指向彩色图标了，第一条的`/Orz-3/task/master`应改为`/Orz-3/mini/master`

**Comment by songyangzz** [comment]
ok 在2020年10月21日 23:14，夜猫 写道： 

icons中的两条链接都指向彩色图标了，第一条的/Orz-3/task/master应改为/Orz-3/mini/master



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/songyangzz/QuantumultX/issues/7",

"url": "https://github.com/songyangzz/QuantumultX/issues/7",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ghost** [comment]
感谢，不过testflight的少了个斜杠😆
